// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qlmuhgvokpsuyrassgwy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFsbXVoZ3Zva3BzdXlyYXNzZ3d5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNjQ4NTYsImV4cCI6MjA2NTc0MDg1Nn0.dezKVE5ZNB711DsuyKXsw9jPwVEXfct8AGdstVVzWGs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);